### ISSUE TITLE
SSD – Erase 기능 추가

### ISSUE THREAD

**Issue by geniuskey** [CRA7C/SSD#56]
Write 명령어 처럼 SSD 자체에 Erase 기능을 추가하고,
Shell에서 명령어를 수행할 수 있도록한다.

- SSD 명령어 : E  [LBA]  [SIZE]
  - 특정LBA 부터 특정 Size 까지 내용을 삭제한다.
  - 삭제할수있는최대Size는최대10칸이다.
  - SSD에서 삭제하면0x00000000이 된다.
- Shell 명령어 1 : erase [LBA]  [SIZE]
  - SSD에 명령어를수행한다.
- Shell 명령어 2 : erase_range [Start LBA]  [End LBA]
  - Start LBA 부터 END LBA 직전 까지 내용을 삭제한다.

**Comment by jwh1308** [comment]
shell app erase/erase_range 기능 main 브랜치에 적용 했습니다.
@currycurry3030 님 SSD 쪽 적용 완료되셨으면 해당 이슈 close 부탁드립니다.

**Comment by currycurry3030** [comment]
넵 close 하겠습니다~!
