### ISSUE TITLE
Logger 기능추가

### ISSUE THREAD

**Issue by geniuskey** [CRA7C/SSD#57]
- [x] Logger 기능 1 : 통일된 로그
- [x] Logger 기능 2 : 로그파일 관리
- [x] Logger 기능 2 : 로그 기록 규칙
- [x] Logger 기능 2 : 로그 압축 규칙

**Comment by gk1whd2** [comment]
고정된 길이가 Function name에 만 적용되어서 ClassName이 길 경우 아래와 같이 틀어지는 현상이 있습니다. 
![image](https://github.com/user-attachments/assets/992f4b37-9689-44dc-85d6-9d3321e4c9df)

**Comment by winsowss** [comment]
첫번쨰 말씀하신건 이번에 올린 PR에 반영되어있습니다.
두번째는 추가해서 PR 올릴게요.

**Comment by geniuskey** [comment]
보통 \t 로 줄넘김하면 생기는 문제이며, 저는 `f"{앞글:30} : {뒷글}" 요렇게 여백 지정하는 것을 선호해요.

**Comment by gk1whd2** [comment]
추가 문제로 
Log파일의 크기가 10KB가 넘어가는 순간에 Log를 남기게 되면 
Log파일에는 남지 않는 현상이 발생하네요.. 
File Rotate가 오래걸려서 그런가봐요
