### ISSUE TITLE
SSD - Command Buffer 기능추가

### ISSUE THREAD

**Issue by geniuskey** [CRA7C/SSD#59]
Command Buffer 를 활용한 최적화
Command Buffer의 도입 목적
- 불필요한Command 개수를 줄여, 성능을 향상
- Command들을 즉시 처리하지 않고, 모아둠으로써 수행을할필요가없는명령어를찾아내어제거한다

**Comment by jwh1308** [comment]
shell app에서 flush 기능 개발 완료했습니다. 참고 바랍니다.

**Comment by gk1whd2** [comment]
https://github.com/CRA7C/SSD/pull/67https://github.com/CRA7C/SSD/pull/67
기존) 명령어가 들어와서 11개가 되면 Flush 
수정) 10에서 더 들어오면 Flush하고 Push
